server:
  port: 8082

spring:

  profiles:
    active: staging
    
  jersey:
    application-path: /api
    
  datasource:
    url: jdbc:h2:mem:test;DB_CLOSE_ON_EXIT=FALSE
    
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      javax:
        persistence:
          sharedCache:
            mode: ENABLE_SELECTIVE
      hibernate:
        format_sql: true
        implicit_naming_strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        temp:
          use_jdbc_metadata_defaults: false
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
          
  cache:
    ehcache:
      config: classpath:ehcache.xml

  h2:
    console:
      enabled: true
      settings:
        web-admin-password: 
        web-allow-others: true
     
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7999/auth/realms/coworking              
     
management:
  endpoints:
    web:
      exposure:
        include: "*"

springdoc:
  api-docs:
    enabled: true
    path: /api/openapi.json
  swagger-ui:
    path: /swagger-ui.html

      
