server:
  port: 8084

spring:

  profiles:
    active: staging
    
  jersey:
    application-path: /api
          
management:
  endpoints:
    web:
      exposure:
        include: "*"

keycloak:
  auth-server-url: http://localhost:7999/auth/
  realm: coworking
  resource: coworking
  ssl-required: none
  cors: true
  bearer-only: true
  credentials:
    secret: 27495668-3a3a-4b63-997e-467880ebcc7c
  principal-attribute: preferred_username
        
springdoc:
  api-docs:
    enabled: true
    path: /api/openapi.json
  swagger-ui:
    path: /swagger-ui.html

